In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/spam-mails-dataset/spam_ham_dataset.csv


In [3]:
from sklearn.model_selection import train_test_split

In [26]:
from sklearn.naive_bayes import MultinomialNB

In [20]:
from sklearn.feature_extraction.text import CountVectorizer

In [4]:
import matplotlib.pyplot as plt

In [35]:
df = pd.read_csv("/kaggle/input/loki-spam/spam.csv")

In [39]:
df.head(5)

Category                                            Message  label_num
0      ham  Go until jurong point, crazy.. Available only ...          0
1      ham                      Ok lar... Joking wif u oni...          0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...          1
3      ham  U dun say so early hor... U c already then say...          0
4      ham  Nah I don't think he goes to usf, he lives aro...          0

In [38]:
df["label_num"] = df["Category"].apply(lambda x: 1 if x=="spam" else 0)

In [13]:
df.drop(["Unnamed: 0"],axis = "columns" ,inplace= True)

In [50]:
 X_train, X_test, y_train, y_test  = train_test_split(df["Category"],df["label_num"],test_size=0.2)

In [51]:
v =CountVectorizer()
x_train_count =v.fit_transform(X_train.values)

In [52]:
model = MultinomialNB()
model.fit(x_train_count,y_train)

MultinomialNB()

In [53]:
x_test_count = v.transform(X_test)

In [54]:
x_test_count.toarray()

array([[1, 0],
       [1, 0],
       [0, 1],
       ...,
       [0, 1],
       [0, 1],
       [1, 0]])

In [55]:
model.score(x_test_count,y_test)

1.0

In [56]:
email= ["hey loki,how are you","Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005.",
       "Todays Voda numbers ending 7548 are selected to receive a $350 award. If you have a match please call 08712300220 quoting claim code 4041 standard rates app"]

email_count = v.transform(email)
model.predict(email_count)

array([0, 0, 0])

In [57]:
test1 = ["Todays Voda numbers ending 7548 are selected to receive a $350 award. If you have a match please call 08712300220 quoting claim code 4041 standard rates app"]
test1_count = v.transform(test1)
model.predict(test1_count)

array([0])